[project]
name = "lanedetection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beamngpy>=1.34.1",
    "matplotlib>=3.10.8",
    "opencv-python>=4.12.0.88",
    "ultralytics>=8.3.236",
]
